### PR TITLE
Making Changes

### PR DESCRIPTION
**Pull request by robssanches**
Hi Takashi

I added a new field type to display messages in text format.

edit field site wordpress

edit page site wordpress

I also created a new attribute in the "Smart_Custom_Fields_Field_Base" class called "layout", which will allow you to choose the type of the custom field layout, which can be full-width or not.

With the possibility of choosing layout, it will be easier to create new types of custom fields that occupy the full width of the meta box.

I also updated some translations.

I hope these changes will be useful to your Smart Custom Fields plugin. I intend to collaborate even more.

Hugs

### CODE REVIEW

**Comment by inc2734** [comment]
I was so busy other project, so forgotten through long time your pull request was submitted ! I am very sorry !

I think that it is a good pull request. I want to reopen this request and checking. Then merge.
Is it OK?

However, I do not want to add SCF_Config::VERSION. I think I will forget to renew. I think that it is better to use the following.
https://developer.wordpress.org/reference/functions/get_plugin_data/

**Comment by inc2734** [comment]
I want to change the message field.



- Removing the label input field.
- Renaming the default input field to "Message"

OK ?

**Comment by robssanches** [comment]
OK Takashi, no problem

I think it's really better to use the get_plugin_data() function instead of SCF_Config::VERSION as you suggested.

About the changes in the message field, they seem to be ok too.

Hugs

**Comment by inc2734** [comment]
> OK Takashi, no problem

Thank you very much !!

> I think it's really better to use the get_plugin_data() function instead of SCF_Config::VERSION as you suggested.

I found a better way. It is a way to use `filemtime()`. By using `filemtime()`, changes of CSS file and JS file should be reflected reliably.

https://github.com/inc2734/smart-custom-fields/commit/7ba867369c78382e7562a0b790579f37d663e04f

Since I am a holiday today, I will continue again tomorrow !

**Pull request merged**
