### PR TITLE
New Changes

### PR DESCRIPTION
**Pull request by robssanches**

### CODE REVIEW

**Comment by inc2734** [comment]
Thank you ! I think it it very nice pull request !
Please wait as I approve it after confirming.

**Comment by robssanches** [comment]
ok

**Comment by inc2734** [comment]
I checked complete. Thanks !
Only one thing, I think it is better to instantiate the model only when it is necessary.

https://github.com/inc2734/smart-custom-fields/commit/25c16e62c58b7d74ea52cd8e72ac67917b67af0e

Is this OK?

**Comment by robssanches** [comment]
Okay, I think that's a good idea.

**Comment by robssanches** [comment]
Hi Takashi,

I added search for posts with ajax in post conditions and also applied IOS styles in checkboxes.






What do you think of these new changes?

**Comment by inc2734** [comment]
Oh, nice UI ! Thanks !!
I am busy now, I will respond next week.

**Comment by robssanches** [comment]
OK

**Pull request merged**
