### PR TITLE
updated the class.scf.php to cater for multiple user roles when showi…

### PR DESCRIPTION
**Pull request by justinticktock**
…ng smart custom forms on user profile pages.  Previously class.scf.php only catered for the primary user role, however, WordPress supports multiple roles to be assigned to the users.

### CODE REVIEW

**Comment by inc2734** [comment]
Thank you for the pull request. But it needs to be modified for the test to fail.

**Comment by justinticktock** [comment]
I missed checking for a valid variable through isset()

**Comment by justinticktock** [comment]
found one more part where type is null so fixed with the addition of the $user_meta_query check.
`!empty( $type ) || isset( $user_meta_query ) `

**Comment by inc2734** [comment]
Thank you !!  I try test !

**Comment by inc2734** [comment]
I understand the WordPress user roles in your favor. Thank you !

I was refactoring the code. I am glad to get tested !

**Comment by justinticktock** [comment]
Looks great, thanks for taking the time to extend for multiple roles.  I've fixed the meta query structure so that the relation of "OR" is correctly picked up.

Looks good to me :)

**Pull request merged**
